<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Qurilmalar katalogi va baholash parametrlari
    |--------------------------------------------------------------------------
    |
    | Telefon, planshet va noutbuklar. Narxlar AQSh dollarida — O'zbekistonning
    | ikkilamchi bozoridagi taxminiy qiymatlar. Ko'rsatishda 'usd_to_uzs' kursi
    | bo'yicha so'mga o'giriladi.
    |
    | Yangi model qo'shish: tegishli brend massiviga ['name' => ..., 'price' => ...]
    | qatorini qo'shing. Tartib — ro'yxatda ko'rinish tartibi.
    |
    */

    'usd_to_uzs' => (int) env('USD_TO_UZS', 12600),

    'storages' => [
        64 => '64 GB',
        128 => '128 GB',
        256 => '256 GB',
        512 => '512 GB',
        1024 => '1 TB',
    ],

    'storage_boost' => [
        64 => 0.0,
        128 => 0.04,
        256 => 0.10,
        512 => 0.17,
        1024 => 0.24,
    ],

    'conditions' => [
        'ideal' => ['label' => 'Ideal', 'icon' => 'fa-solid fa-gem'],
        'good' => ['label' => 'Yaxshi', 'icon' => 'fa-solid fa-thumbs-up'],
        'scratched' => ['label' => 'Tirnalgan', 'icon' => 'fa-solid fa-band-aid'],
    ],

    'condition_delta' => [
        'ideal' => 0.06,
        'good' => 0.0,
        'scratched' => -0.12,
    ],

    'brands' => [
        'Apple' => [
            ['name' => 'iPhone 16 Pro Max', 'price' => 1250],
            ['name' => 'iPhone 16 Pro', 'price' => 1100],
            ['name' => 'iPhone 16 Plus', 'price' => 950],
            ['name' => 'iPhone 16', 'price' => 850],
            ['name' => 'iPhone 16e', 'price' => 600],
            ['name' => 'iPhone 15 Pro Max', 'price' => 1050],
            ['name' => 'iPhone 15 Pro', 'price' => 900],
            ['name' => 'iPhone 15 Plus', 'price' => 780],
            ['name' => 'iPhone 15', 'price' => 700],
            ['name' => 'iPhone 14 Pro Max', 'price' => 800],
            ['name' => 'iPhone 14 Pro', 'price' => 700],
            ['name' => 'iPhone 14 Plus', 'price' => 600],
            ['name' => 'iPhone 14', 'price' => 550],
            ['name' => 'iPhone 13 Pro Max', 'price' => 620],
            ['name' => 'iPhone 13 Pro', 'price' => 560],
            ['name' => 'iPhone 13', 'price' => 420],
            ['name' => 'iPhone 13 mini', 'price' => 330],
            ['name' => 'iPhone 12 Pro Max', 'price' => 480],
            ['name' => 'iPhone 12 Pro', 'price' => 420],
            ['name' => 'iPhone 12', 'price' => 320],
            ['name' => 'iPhone 12 mini', 'price' => 250],
            ['name' => 'iPhone 11 Pro Max', 'price' => 330],
            ['name' => 'iPhone 11 Pro', 'price' => 290],
            ['name' => 'iPhone 11', 'price' => 230],
            ['name' => 'iPhone XS Max', 'price' => 220],
            ['name' => 'iPhone XS', 'price' => 190],
            ['name' => 'iPhone XR', 'price' => 180],
            ['name' => 'iPhone X', 'price' => 170],
            ['name' => 'iPhone 8 Plus', 'price' => 140],
            ['name' => 'iPhone 8', 'price' => 110],
            ['name' => 'iPhone SE (2022)', 'price' => 200],
            ['name' => 'iPhone SE (2020)', 'price' => 130],

            // Planshetlar
            ['name' => 'iPad Pro 12.9', 'price' => 700],
            ['name' => 'iPad Pro 11', 'price' => 550],
            ['name' => 'iPad Air 5', 'price' => 450],
            ['name' => 'iPad Air 4', 'price' => 350],
            ['name' => 'iPad 10', 'price' => 300],
            ['name' => 'iPad 9', 'price' => 200],
            ['name' => 'iPad mini 6', 'price' => 350],

            // Noutbuklar
            ['name' => 'MacBook Pro 16', 'price' => 1500],
            ['name' => 'MacBook Pro 14', 'price' => 1150],
            ['name' => 'MacBook Pro 13', 'price' => 550],
            ['name' => 'MacBook Air M3', 'price' => 750],
            ['name' => 'MacBook Air M2', 'price' => 600],
            ['name' => 'MacBook Air M1', 'price' => 450],
        ],
        'Samsung' => [
            ['name' => 'Galaxy S25 Ultra', 'price' => 950],
            ['name' => 'Galaxy S25+', 'price' => 800],
            ['name' => 'Galaxy S25', 'price' => 700],
            ['name' => 'Galaxy S24 Ultra', 'price' => 750],
            ['name' => 'Galaxy S24+', 'price' => 620],
            ['name' => 'Galaxy S24', 'price' => 600],
            ['name' => 'Galaxy S24 FE', 'price' => 450],
            ['name' => 'Galaxy S23 Ultra', 'price' => 600],
            ['name' => 'Galaxy S23+', 'price' => 500],
            ['name' => 'Galaxy S23', 'price' => 450],
            ['name' => 'Galaxy S23 FE', 'price' => 350],
            ['name' => 'Galaxy S22 Ultra', 'price' => 470],
            ['name' => 'Galaxy S22+', 'price' => 390],
            ['name' => 'Galaxy S22', 'price' => 350],
            ['name' => 'Galaxy S21 Ultra', 'price' => 380],
            ['name' => 'Galaxy S21+', 'price' => 320],
            ['name' => 'Galaxy S21', 'price' => 290],
            ['name' => 'Galaxy S21 FE', 'price' => 250],
            ['name' => 'Galaxy S20 Ultra', 'price' => 300],
            ['name' => 'Galaxy S20+', 'price' => 260],
            ['name' => 'Galaxy S20', 'price' => 230],
            ['name' => 'Galaxy S20 FE', 'price' => 200],
            ['name' => 'Galaxy Note 20 Ultra', 'price' => 320],
            ['name' => 'Galaxy Note 20', 'price' => 260],
            ['name' => 'Galaxy Note 10+', 'price' => 240],
            ['name' => 'Galaxy Note 10', 'price' => 200],
            ['name' => 'Galaxy Note 9', 'price' => 150],
            ['name' => 'Galaxy Z Fold 6', 'price' => 1100],
            ['name' => 'Galaxy Z Fold 5', 'price' => 850],
            ['name' => 'Galaxy Z Fold 4', 'price' => 650],
            ['name' => 'Galaxy Z Flip 6', 'price' => 750],
            ['name' => 'Galaxy Z Flip 5', 'price' => 600],
            ['name' => 'Galaxy Z Flip 4', 'price' => 450],
            ['name' => 'Galaxy A55', 'price' => 250],
            ['name' => 'Galaxy A54', 'price' => 220],
            ['name' => 'Galaxy A35', 'price' => 190],
            ['name' => 'Galaxy A34', 'price' => 170],
            ['name' => 'Galaxy A25', 'price' => 150],
            ['name' => 'Galaxy A24', 'price' => 140],
            ['name' => 'Galaxy A15', 'price' => 120],
            ['name' => 'Galaxy A14', 'price' => 110],
            ['name' => 'Galaxy A05', 'price' => 90],
            ['name' => 'Galaxy M35', 'price' => 160],
            ['name' => 'Galaxy M15', 'price' => 110],

            // Planshetlar
            ['name' => 'Galaxy Tab S9 Ultra', 'price' => 550],
            ['name' => 'Galaxy Tab S9', 'price' => 450],
            ['name' => 'Galaxy Tab S8', 'price' => 350],
            ['name' => 'Galaxy Tab S7 FE', 'price' => 250],
            ['name' => 'Galaxy Tab S6 Lite', 'price' => 180],
            ['name' => 'Galaxy Tab A9+', 'price' => 150],
            ['name' => 'Galaxy Tab A8', 'price' => 120],
        ],
        'Xiaomi' => [
            ['name' => 'Xiaomi 15 Ultra', 'price' => 900],
            ['name' => 'Xiaomi 15', 'price' => 700],
            ['name' => 'Xiaomi 14 Ultra', 'price' => 800],
            ['name' => 'Xiaomi 14', 'price' => 600],
            ['name' => 'Xiaomi 13T Pro', 'price' => 500],
            ['name' => 'Xiaomi 13T', 'price' => 400],
            ['name' => 'Xiaomi 13 Pro', 'price' => 450],
            ['name' => 'Xiaomi 13', 'price' => 380],
            ['name' => 'Xiaomi 12T Pro', 'price' => 380],
            ['name' => 'Xiaomi 12T', 'price' => 300],
            ['name' => 'Xiaomi 12 Pro', 'price' => 350],
            ['name' => 'Xiaomi 12', 'price' => 300],
            ['name' => 'Xiaomi 11T Pro', 'price' => 280],
            ['name' => 'Xiaomi 11 Lite', 'price' => 200],
            ['name' => 'Redmi Note 14 Pro+', 'price' => 280],
            ['name' => 'Redmi Note 14 Pro', 'price' => 240],
            ['name' => 'Redmi Note 14', 'price' => 200],
            ['name' => 'Redmi Note 13 Pro+', 'price' => 250],
            ['name' => 'Redmi Note 13 Pro', 'price' => 220],
            ['name' => 'Redmi Note 13', 'price' => 180],
            ['name' => 'Redmi Note 12 Pro', 'price' => 170],
            ['name' => 'Redmi Note 12', 'price' => 140],
            ['name' => 'Redmi Note 11 Pro', 'price' => 130],
            ['name' => 'Redmi Note 11', 'price' => 110],
            ['name' => 'Redmi Note 10 Pro', 'price' => 120],
            ['name' => 'Redmi 14C', 'price' => 100],
            ['name' => 'Redmi 13C', 'price' => 90],
            ['name' => 'Redmi 12', 'price' => 120],
            ['name' => 'Redmi 10', 'price' => 80],
            ['name' => 'Redmi 9A', 'price' => 60],
            ['name' => 'Redmi 9C', 'price' => 70],
            ['name' => 'POCO F6 Pro', 'price' => 400],
            ['name' => 'POCO F6', 'price' => 330],
            ['name' => 'POCO F5', 'price' => 280],
            ['name' => 'POCO X6 Pro', 'price' => 250],
            ['name' => 'POCO X6', 'price' => 200],
            ['name' => 'POCO M6 Pro', 'price' => 150],
            ['name' => 'POCO C65', 'price' => 120],

            // Planshetlar
            ['name' => 'Xiaomi Pad 6', 'price' => 280],
            ['name' => 'Xiaomi Pad 5', 'price' => 200],
            ['name' => 'Redmi Pad SE', 'price' => 130],
        ],
        'Oppo' => [
            ['name' => 'Find X8 Pro', 'price' => 800],
            ['name' => 'Find X7', 'price' => 600],
            ['name' => 'Find X6 Pro', 'price' => 500],
            ['name' => 'Reno 12 Pro', 'price' => 400],
            ['name' => 'Reno 12', 'price' => 330],
            ['name' => 'Reno 11', 'price' => 300],
            ['name' => 'Reno 10', 'price' => 250],
            ['name' => 'Reno 8T', 'price' => 200],
            ['name' => 'A98', 'price' => 180],
            ['name' => 'A78', 'price' => 150],
            ['name' => 'A58', 'price' => 120],
            ['name' => 'A38', 'price' => 100],
            ['name' => 'A18', 'price' => 85],
        ],
        'Vivo' => [
            ['name' => 'X200 Pro', 'price' => 900],
            ['name' => 'X100 Pro', 'price' => 600],
            ['name' => 'X100', 'price' => 500],
            ['name' => 'V40', 'price' => 400],
            ['name' => 'V30 Pro', 'price' => 350],
            ['name' => 'V30', 'price' => 300],
            ['name' => 'V29', 'price' => 300],
            ['name' => 'V27', 'price' => 250],
            ['name' => 'Y36', 'price' => 150],
            ['name' => 'Y28', 'price' => 130],
            ['name' => 'Y27', 'price' => 120],
            ['name' => 'Y17s', 'price' => 100],
        ],
        'Honor' => [
            ['name' => 'Magic 6 Pro', 'price' => 550],
            ['name' => 'Magic 5 Pro', 'price' => 420],
            ['name' => 'Honor 200 Pro', 'price' => 380],
            ['name' => 'Honor 200', 'price' => 300],
            ['name' => 'Honor 90', 'price' => 280],
            ['name' => 'Honor 70', 'price' => 220],
            ['name' => 'X9b', 'price' => 200],
            ['name' => 'X9a', 'price' => 180],
            ['name' => 'X8b', 'price' => 160],
            ['name' => 'X8a', 'price' => 140],
            ['name' => 'X7b', 'price' => 120],
            ['name' => 'X6b', 'price' => 110],
        ],
        'Huawei' => [
            ['name' => 'Pura 70 Ultra', 'price' => 700],
            ['name' => 'P60 Pro', 'price' => 450],
            ['name' => 'Mate 50 Pro', 'price' => 400],
            ['name' => 'P50 Pro', 'price' => 350],
            ['name' => 'Nova 12', 'price' => 250],
            ['name' => 'Nova 11', 'price' => 200],
            ['name' => 'Nova 9', 'price' => 170],
            ['name' => 'Y9a', 'price' => 120],
        ],
        'Realme' => [
            ['name' => 'GT5 Pro', 'price' => 450],
            ['name' => 'GT6', 'price' => 400],
            ['name' => '13 Pro+', 'price' => 300],
            ['name' => '12 Pro+', 'price' => 300],
            ['name' => '11 Pro', 'price' => 220],
            ['name' => '10 Pro', 'price' => 190],
            ['name' => 'Narzo 60', 'price' => 150],
            ['name' => 'C67', 'price' => 130],
            ['name' => 'C55', 'price' => 110],
            ['name' => 'C53', 'price' => 100],
        ],
        'Infinix' => [
            ['name' => 'Zero 40', 'price' => 250],
            ['name' => 'Zero 30', 'price' => 200],
            ['name' => 'Note 40 Pro', 'price' => 180],
            ['name' => 'Note 30', 'price' => 150],
            ['name' => 'Hot 50', 'price' => 130],
            ['name' => 'Hot 40', 'price' => 120],
            ['name' => 'Smart 8', 'price' => 80],
            ['name' => 'Smart 7', 'price' => 70],
        ],
        'Tecno' => [
            ['name' => 'Camon 30 Pro', 'price' => 220],
            ['name' => 'Pova 6 Pro', 'price' => 200],
            ['name' => 'Camon 20 Pro', 'price' => 180],
            ['name' => 'Pova 5', 'price' => 150],
            ['name' => 'Spark 20 Pro', 'price' => 140],
            ['name' => 'Spark 20', 'price' => 120],
            ['name' => 'Pop 8', 'price' => 90],
        ],
        'Google' => [
            ['name' => 'Pixel 9 Pro', 'price' => 800],
            ['name' => 'Pixel 9', 'price' => 700],
            ['name' => 'Pixel 8 Pro', 'price' => 600],
            ['name' => 'Pixel 8', 'price' => 480],
            ['name' => 'Pixel 7 Pro', 'price' => 400],
            ['name' => 'Pixel 7', 'price' => 320],
            ['name' => 'Pixel 7a', 'price' => 300],
            ['name' => 'Pixel 6a', 'price' => 220],
        ],
        'OnePlus' => [
            ['name' => 'OnePlus 13', 'price' => 700],
            ['name' => 'OnePlus 12', 'price' => 600],
            ['name' => 'OnePlus 11', 'price' => 400],
            ['name' => 'OnePlus 10 Pro', 'price' => 350],
            ['name' => 'Nord 4', 'price' => 350],
            ['name' => 'Nord 3', 'price' => 250],
            ['name' => 'Nord CE 3', 'price' => 200],
        ],
        'Nokia' => [
            ['name' => 'G42', 'price' => 120],
            ['name' => 'C32', 'price' => 90],
            ['name' => '105', 'price' => 25],
        ],

        // --- Noutbuklar ---
        'Lenovo' => [
            ['name' => 'Legion Pro 5', 'price' => 800],
            ['name' => 'Legion 5', 'price' => 600],
            ['name' => 'ThinkPad X1 Carbon', 'price' => 600],
            ['name' => 'Yoga Slim 7', 'price' => 450],
            ['name' => 'ThinkPad T14', 'price' => 400],
            ['name' => 'IdeaPad Slim 3', 'price' => 300],
            ['name' => 'IdeaPad 3', 'price' => 250],
        ],
        'HP' => [
            ['name' => 'Omen 16', 'price' => 700],
            ['name' => 'Victus 15', 'price' => 450],
            ['name' => 'Pavilion Aero 13', 'price' => 400],
            ['name' => 'EliteBook 840', 'price' => 350],
            ['name' => 'Pavilion 15', 'price' => 300],
            ['name' => 'ProBook 450', 'price' => 300],
        ],
        'Asus' => [
            ['name' => 'ROG Strix G15', 'price' => 700],
            ['name' => 'TUF Gaming F15', 'price' => 550],
            ['name' => 'Zenbook 14', 'price' => 450],
            ['name' => 'VivoBook S14', 'price' => 380],
            ['name' => 'VivoBook 15', 'price' => 280],
        ],
        'Acer' => [
            ['name' => 'Predator Helios 300', 'price' => 700],
            ['name' => 'Nitro 5', 'price' => 500],
            ['name' => 'Swift 3', 'price' => 350],
            ['name' => 'Aspire 7', 'price' => 350],
            ['name' => 'Aspire 5', 'price' => 270],
        ],
        'Dell' => [
            ['name' => 'XPS 15', 'price' => 700],
            ['name' => 'XPS 13', 'price' => 500],
            ['name' => 'Latitude 5420', 'price' => 350],
            ['name' => 'Inspiron 15', 'price' => 300],
            ['name' => 'Vostro 15', 'price' => 280],
        ],
        'Microsoft' => [
            ['name' => 'Surface Pro 9', 'price' => 700],
            ['name' => 'Surface Laptop 5', 'price' => 600],
            ['name' => 'Surface Pro 8', 'price' => 500],
        ],
    ],

];
